let a =prompt("Nhập điểm hóa")
let b =prompt("nhập điểm lý")
let c=prompt("nhập điểm sinh")
a = parseFloat(a)
b = parseFloat(b)
c = parseFloat(c)
let d = (a + b + c)/3
let s = (a + b + c)
alert("Điểm trung bình bằng: " + d)
alert("Điểm tổng bằng: " +s)